name: Build

on:
  push:
    paths:
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.hxx'
      - '**/*.cu'
      - '**/*.cuh'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - 'build.bat'

  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.hxx'
      - '**/*.cu'
      - '**/*.cuh'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - 'build.bat'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: cmd
        run: build.bat
