name: Docs

on:
  push:
  pull_request:

jobs:
  docs:
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install MiKTeX
        uses: zauguin/install-miktex@v2

      - name: Enable MiKTeX auto-install
        shell: cmd
        run: |
          initexmf --set-config-value=[MPM]AutoInstall=1

      - name: Build documentation
        shell: cmd
        run: doc\lat.bat
