name: Docs
on:
  push:
    paths:
      - 'doc/**'
  pull_request:
    paths:
      - 'doc/**'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-bibtex-extra \
            texlive-fonts-extra \
            texlive-luatex \
            texlive-science
            
      - name: Build documentation
        working-directory: doc
        run: |
          pdflatex rapport
          bibtex rapport
          pdflatex rapport
          pdflatex rapport
          texlua checkcites.lua --unused rapport.aux
